version: '3'
networks:
  common-net:
    driver: bridge
services:
  zook1:
    image: zookeeper
    restart: always
    hostname: zook1
    container_name: zook1
    ports:
      - 4181:4181
    volumes:
      - I:\docekerWorkSpace\learForAll\store\zookeeper\zookeeper1\data:/data
      - I:\docekerWorkSpace\learForAll\store\zookeeper\zookeeper1\datalog:/datalog
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zook1:2888:3888;4181 server.2=zook2:2888:3888;4181 server.3=zook3:2888:3888;4181
    networks:
      - common-net

  zook2:
    image: zookeeper
    restart: always
    hostname: zook2
    container_name: zook2
    ports:
      - 4182:4181
    volumes:
      - I:\docekerWorkSpace\learForAll\store\zookeeper\zookeeper2\data:/data
      - I:\docekerWorkSpace\learForAll\store\zookeeper\zookeeper2\datalog:/datalog
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zook1:2888:3888;4181 server.2=zook2:2888:3888;4181 server.3=zook3:2888:3888;4181
    networks:
      - common-net
  zook3:
    image: zookeeper
    restart: always
    hostname: zook3
    container_name: zook3
    ports:
      - 4183:4181
    volumes:
      - I:\docekerWorkSpace\learForAll\store\zookeeper\zookeeper3\data:/data
      - I:\docekerWorkSpace\learForAll\store\zookeeper\zookeeper3\datalog:/datalog
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zook1:2888:3888;4181 server.2=zook2:2888:3888;4181 server.3=zook3:2888:3888;4181
    networks:
      - common-net

  kafka1:
    image: bitnami/kafka:latest
    container_name: kafka1
    hostname: kafka1
    ports:
      - 9093:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zook1:4181,zook2:4182,zook3:4183
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka1:9092,EXTERNAL://kafka1:9093
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - I:\docekerWorkSpace\learForAll\store\kafka\kafka1\data:/bitnami/kafka
    networks:
      - common-net
    depends_on:
      - zook1
      - zook2
      - zook3

  kafka2:
    image: bitnami/kafka:latest
    container_name: kafka2
    hostname: kafka2
    ports:
      - 9094:9092
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zook1:4181,zook2:4182,zook3:4183
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka2:9092,EXTERNAL://kafka2:9094
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9094
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - I:\docekerWorkSpace\learForAll\store\kafka\kafka2\data:/bitnami/kafka
    networks:
      - common-net
    depends_on:
      - zook1
      - zook2
      - zook3

  kafka3:
    image: bitnami/kafka:latest
    container_name: kafka3
    hostname: kafka3
    ports:
      - 9095:9092
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zook1:4181,zook2:4182,zook3:4183
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka3:9092,EXTERNAL://kafka3:9095
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9095
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - I:\docekerWorkSpace\learForAll\store\kafka\kafka3\data:/bitnami/kafka
    networks:
      - common-net
    depends_on:
      - zook1
      - zook2
      - zook3